Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -501,13 +501,14 @@ jobs:
           ls -la "${{ github.workspace }}"
           ls -la "${{ github.workspace }}/tweaks"
 
-          DYLIB_PATH="${{ github.workspace }}/tweaks/YouPro_Patched.dylib"
-          BUNDLE_PATH="${{ github.workspace }}/tweaks/YouPro.bundle"
+          #DYLIB_PATH="${{ github.workspace }}/tweaks/YouPro_Patched.dylib"
+          #BUNDLE_PATH="${{ github.workspace }}/tweaks/YouPro.bundle"
 
-          [ -f "$DYLIB_PATH" ] || { echo "Missing $DYLIB_PATH"; exit 1; }
-          [ -d "$BUNDLE_PATH" ] || { echo "Missing $BUNDLE_PATH"; exit 1; }
+          #[ -f "$DYLIB_PATH" ] || { echo "Missing $DYLIB_PATH"; exit 1; }
+          #[ -d "$BUNDLE_PATH" ] || { echo "Missing $BUNDLE_PATH"; exit 1; }
 
-          tweaks="OpenYouTubeSafariExtension.appex $DYLIB_PATH $BUNDLE_PATH"
+          #tweaks="OpenYouTubeSafariExtension.appex $DYLIB_PATH $BUNDLE_PATH"
+          tweaks="OpenYouTubeSafariExtension.appex"
 
           for f in *.deb; do
             if [ -f "$f" ]; then
